/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: ea7e911828aeb0104d08629292fac600)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "CloudArchitectAgent";
	}
	interface Env {
		OPENAI_API_KEY: string;
		GATEWAY_BASE_URL: string;
		CloudArchitectAgent: DurableObjectNamespace<import("./src/server").CloudArchitectAgent>;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env { }
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_API_KEY" | "GATEWAY_BASE_URL">> { }
}
